export const trendingTopics = [
    'AI & Machine Learning',
    'Web Development',
    'React',
    'Next.js',
    'TypeScript',
    'Database Design',
    'DevOps',
    'Mobile Development',
];

export const recommendedBlogs = [
    {
        id: 1,
        title: "The Future of Web Development: What's Coming in 2024",
        excerpt: 'Exploring the latest trends and technologies that will shape web development in the coming year...',
        author: {
            name: 'Sarah Chen',
            avatar: '/woman-developer.png',
            username: 'sarahchen',
        },
        publishedAt: '2 hours ago',
        readTime: '5 min read',
        likes: 124,
        comments: 18,
        tags: ['Web Development', 'Technology', 'Future'],
        image: '/futuristic-web-development.png',
        featured: true,
    },
    {
        id: 2,
        title: 'Building Scalable React Applications: Best Practices',
        excerpt: 'Learn how to structure your React applications for maximum scalability and maintainability...',
        author: {
            name: 'Mike Johnson',
            avatar: '/man-programmer.png',
            username: 'mikej',
        },
        publishedAt: '4 hours ago',
        readTime: '8 min read',
        likes: 89,
        comments: 12,
        tags: ['React', 'JavaScript', 'Best Practices'],
        image: '/react-code-architecture.png',
    },
    {
        id: 3,
        title: "The Art of Technical Writing: A Developer's Guide",
        excerpt:
            'Master the skills needed to write clear, engaging technical content that developers actually want to read...',
        author: {
            name: 'Emily Rodriguez',
            avatar: '/woman-writer.png',
            username: 'emilyrod',
        },
        publishedAt: '6 hours ago',
        readTime: '6 min read',
        likes: 156,
        comments: 24,
        tags: ['Writing', 'Documentation', 'Communication'],
        image: '/placeholder-uv20w.png',
    },
    {
        id: 4,
        title: 'Understanding Database Design Patterns',
        excerpt: 'Deep dive into common database design patterns and when to use them in your applications...',
        author: {
            name: 'David Kim',
            avatar: '/man-database-engineer.png',
            username: 'davidkim',
        },
        publishedAt: '1 day ago',
        readTime: '10 min read',
        likes: 203,
        comments: 31,
        tags: ['Database', 'Design Patterns', 'Backend'],
        image: '/database-schema.png',
    },
];
