export const authorData = {
    name: 'Sarah Chen',
    username: 'sarahchen',
    avatar: '/woman-developer.png',
    bio: 'Full-stack developer passionate about creating beautiful, functional web applications. I love sharing knowledge about React, Next.js, and modern web development practices.',
    location: 'San Francisco, CA',
    joinedDate: 'March 2022',
    website: 'https://sarahchen.dev',
    followers: 1234,
    following: 567,
    totalPosts: 42,
    totalLikes: 5678,
};

export const authorPosts = [
    {
        id: 1,
        title: "The Future of Web Development: What's Coming in 2024",
        excerpt: 'Exploring the latest trends and technologies that will shape web development in the coming year...',
        publishedAt: '2 hours ago',
        readTime: '5 min read',
        likes: 124,
        comments: 18,
        tags: ['Web Development', 'Technology', 'Future'],
        image: '/futuristic-web-development.png',
    },
    {
        id: 5,
        title: 'Building Responsive Layouts with CSS Grid',
        excerpt: 'Master CSS Grid to create complex, responsive layouts with ease...',
        publishedAt: '3 days ago',
        readTime: '7 min read',
        likes: 89,
        comments: 12,
        tags: ['CSS', 'Grid', 'Responsive Design'],
        image: '/css-grid-layout.png',
    },
    {
        id: 6,
        title: 'State Management in React: A Complete Guide',
        excerpt: 'Everything you need to know about managing state in React applications...',
        publishedAt: '1 week ago',
        readTime: '12 min read',
        likes: 203,
        comments: 31,
        tags: ['React', 'State Management', 'JavaScript'],
        image: '/react-state-management.png',
    },
];
